# Generated by Django 3.2 on 2022-05-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='last_used_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
