---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-django-auth
  labels:
    app: nginx-ingress-django-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress-django-auth
  template:
    metadata:
      labels:
        app: nginx-ingress-django-auth
    spec:
      containers:
        - image: gabrielmilan/nginx-ingress-django-auth:v0.0.4
          name: nginx-ingress-django-auth
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DJANGO_AUTH_PUBLIC_URI
              value: "https://auth.example.com"
            - name: COOKIE_DOMAIN
              value: ".example.com"
            - name: DJANGO_SUPERUSER_USERNAME
              value: "admin"
            - name: DJANGO_SUPERUSER_PASSWORD
              value: "admin"
            - name: DJANGO_SUPERUSER_EMAIL
              value: "admin@example.com"
            - name: DJANGO_SETTINGS_MODULE
              value: "forward_auth.settings.prod"
            - name: CONFIG
              valueFrom:
                secretKeyRef:
                  name: nginx-ingress-django-auth-config
                  key: config.json
