apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-ingress-django

commonLabels:
  kustomize.component: nginx-ingress-django

resources:
  - deployment.yaml
  - issuer.yaml
  - service.yaml

secretGenerator:
  - name: nginx-ingress-django-auth-config
    files:
      - config.json
